version: '3.9'

services:
  #Mongo DB service
  mongo_db:
    container_name: coopers-database
    image: mongo:latest
    restart: always
    ports:
      - 2717:27017
    volumes:
      - mongo_db:/data/db

  api:
    container_name: coopers-backend
    build: .
    ports:
      - 4000:3000
    environment:
      PORT: 3000
      MONGODB_URI: mongodb://coopers-database:27017
      DB_NAME: coopers_db
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}